table cause_code_modification
	lineageTag: 2179af1f-0926-436c-9229-7250b92470db

	column 'ICD10 Code'
		dataType: string
		lineageTag: 65d68973-aa49-4889-b6e8-649445924db8
		summarizeBy: none
		sourceColumn: ICD10 Code

		annotation SummarizationSetBy = Automatic

	column 'ICD10 Code.2'
		dataType: string
		lineageTag: d608b2d4-2429-4574-9eee-7f10b98925c3
		summarizeBy: none
		sourceColumn: ICD10 Code.2

		annotation SummarizationSetBy = Automatic

	column lookup_cause_code
		dataType: string
		lineageTag: 09853f56-0440-4df1-945a-01b88fb2c7d3
		summarizeBy: none
		sourceColumn: lookup_cause_code

		annotation SummarizationSetBy = Automatic

	partition cause_code_modification = m
		mode: import
		queryGroup: DEV
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("TZxLkvYgb0b3knEGDYiLNhLT9Vf2v434S/kc9ehV20iPja4I2v/5z3/9z8/Pf/3vf///bxFFNakuNaRCakotqS11pBJKwU2wVtcEa4I1wZpgTbAmWBOsCVaEYClYCpaCpWApWAqWgqVgCQZyfS9fy+cBsDOkM6QzhCcZDBkMGQzhEYMhwZBgCM8+GTIZMhnCSy2GLIYshvjLEOfOqXPmmAbevv1INIgOMSACYkIgBibl1RXEYCINC2kYSGPGHcuMN2a8dW8hpiOmIwatiIRWGlppAzHDMYgZiEFzPieaa2iuBWICMeFgxKBd3xLtNrTbJmImYiZiplyIWfwiBgtoCzELMQsxCzFYCQ7YNmI2YjZiNmI2YjZiNmIOv4g5iDmIOYg5iDmIOYjxFzHYbMNmGzbbcPaGrzdcveHfDbvGgPpPEUU1qS51pBThsCZrq2uyNlmbrN6sB+my9rora5d1SMg6ZB2yDlmHrCEha8gasoasIeuUkHXKOmWdsk5Zi5A1ZU1ZU1aVxCjn1zDUjUPdQPRSR0oRDishf67JqpIMNr1uqqRWj9TrrqwqiQjTDTHdGNMNMi8lq0oiqnTDSjeudAPLS8mqkogk3VDSjSXdYPJSsqqkemmVpKt1fa3rSL08iXtOUvlUuUhZfFdJZRnOamm6FFd66CqpnrfgC7/E/bkrq0oiU7yErCqpq6SukrpKIre8hKwqqaukrpK6SiIbvYSsKqmrpK6SukqqJ1dJXSV1ldRVUldJvKpvOn6KalJd6kgpwmEqabS6JqtKGirJuRwqaaik0euurL7q8Mnr0etJSrBKGiqJzP0SsqqkoZKGShoqiVz/ErKqpKGShkoaKqngVdJQSUMlDZU0VBLP6+PGT1FNqksdKUU4TCVFq2uyqqRQSU5IqKRQSdHrrqwqiSrnJWRVSaGSQiWFsxS+dL11vUQ9k0oKlUQl9RKyqqRQSaGSQiWVDJUUKilUUqikUEmAijl/impSXepIKcJhKmm2uiarSpoqybeaKmmqpNnrrqwqiRryJWRVSVMlTZU0VRJV50vIqpKmSpoqaTrB0/mqCav3r9dRSVMl/SFkVUlTJU2VNFXS4vdHoqgm1aWOlCIcppJWq2uyqqSlkpY3VdJSSavXXVlVEhX6S8iqkpZKWippqSRq+peQVSUtlbRU0lJJrAJeQlaVtFTSUklL3awiZFVJSyUtlbRU0ub3R6KoJtWljpQiHKaSdqtrsqqkrZK2N1XSVkm7111ZVRLrn5eQVSVtlbRV0lZJrJheQlaVtFXSVklbJbHGeglZVdJWSVslbZW0i5BVJW2VtFXSVklcYR33EkU1qS5VDIpwmEo6ra7JqpKOSjreVElHJZ1ed2VVSawuX0JWlXRU0lFJRyWxHn0JWVXSUUlHJR2VxAr2JWRVSUclHZV0VNIpQlaVdFTSUUlHJfkLo3yysUrurJI7q+TOKrnqRgQzcxaL1oqWioP16GB1OVgrDppSgxaixSSKsJS0krSQHKyhBiuiwfpm0OsYdCssNdGrhaZ1pmXmoBgeFFyDpD5IHIPgZCFKHWoZahVqETpqDIKpI8dA8EAw1uZYbM0a1RJ1UF+NcDCCA8GBYGxRbCzRCtYCdlATDDL8mHIheCIYS/VdyK6DXDnIfIM8NshKgxwzluwIJoc4N2SEQXwfROtB7B1E0kFcHBvBWzkIPvwimJg0iDCDeDHw/oEvj4Pgg2B8VSXieZb6VvoDzxt43sDzBp7nYsC1AMbgCiB+/lBNqksNqSOlMBmaQlpdU0hTSFNIU4jDukK6QnrdVUhXSFeIN4dChkKGQkaNU8hQSEgoJBQSCgmFhEJCIVNCIVMhUyFTIVMhUyFLQiFLIUshSyFLIUshW0IhWyFbIVshWyFbIUUoJBWSCkmFpEI0OsZrJfbbwn5b2G8LO/9h5y3svLnsjFbi/lxTiEZnDy7swUUN0+jswYU9uLDrH3bjwm5cFIJGZzcu7MaFPf+wLxf25YIsFPblotWEaXR2/MMOXdihCzJY2KELO3Rhhy7s94e9urBXF2S/sNUf9vrDZn/Y7X8phWh0ZM6w0R92+sNWf9jrfymFaHSlJo3OrmHYNQxb9GH/MOwfOnMq2P5h2D8M+4dhAzzsJIadRBsWYScx7CSGncSwQRv2FMOeor2O6PVMJfjPXYVodPboom5qdLbQwo5Y2OAK+4xhDymoUMKeUNjiiV5Tp9HZcQx7HEF1E/YswhZE2FEIGwRh7zFcgweVUbimDpfI4Yo3XMC+lEI0OqqqcM0XLuHCFVm4wHophWh0NcManfVuWPCGFW9Y14aFrfOlbixxwxo3LHLDKjfsjIbFrK2usJwN69mwoA0r2rBHGhaudsnC0jWsXcPiNaxew25pWKSGxjTqxerpCuLPOIVodFSkYUka1qRhURqjJlGjs/gMqs+w/Azrz7AADSvQsJcaFppBpRmWmmGtGRabYbX5UgrR6Kgqw7IyrCvDwjKsLF9KIRpdTY5GZ6kX1nphsReWdFE1HfPqtFZ1VyVa1VlVLNnpjcrzaqSydaXcypuV/Oz5RsVtlVnRt0JoxcEKZnZ/o/xQOyhvKpcouy7jtA8cNa81OTU79Yr1nAWm0dkRDlZFYUc47AiHHeGXUohGZ284WFG9hEI0utDoQqMLjS40OlZjL6EQjS40utDoQqMLja7eS6OzSx12qV9KIRqd/WqnxBmxXx32q8N+9UsNqSOlMBk0OjvXYef6pRSi0dnDLj3Yww572GEP+6UUotHZzS4V2s0Ou9lhN/ulapxCNDpWvWFfO+xrh33tl1KIRmeHO6YzXFNc81QvW0+s0dnrDlbbL6EQjW5qdFOjmxrd1OhYqb+EQjS6qdFNjW5qdFOjq0fS6Oy6h133l1KIRmf/XRfyZey/h/33sP/+UkPqSClMBo3OTnzYiX8phWh09uTLb+3Jhz35sCf/UgrR6OzOl8vbnQ+782F3/qVqnEI0OjoiYZ8+7NOHffqXUohGZ8c+6KaEHfuwYx927F9KIRqdvftYqqn0VJNdM1avrdEtjY4uzksoRKNbGt3S6JZGtzS6kqbRuYsQ7iK8lEI0OvcTDLk+h/sJ4X5CuJ/wUkPqSClMBo3OnYVwZ+GlFKLRucdQcd49hnCPIdxjeCmFaHTuNlSKcLch3G0IdxteqsYpRKOjWxbuO4T7DuG+w0spRKNzByLotIU7EOEORLgD8VIK0ejciwi6dC+hEI1ua3Rbo9sa3dZMtrouZZfGatpr7jS6rdH9IRSi0bkr8lIK0ejcH3GW6CyG+yPh/ki4P/JSQ6pYFSaDRudOSbhT8lIK0ejcM4njMI3OPZNwz+SlFKLRuXsSx5sanbsn4e7JS9U4hWh0dFLDfZRwHyXcR3kphdR0anR0YcMdlXBHJdxReSmFaHTurQQd3JdQiEZ3NLqj0R2N7mh0dH9fQiEa3dHojkZ3NLqjrZ0iFKLRucvzUgrR6NzvcW4UoQQFyE/XOeg6B13nqhYRzAxbIlohWiBaH066sJNO6qQbOuloWjiiMMtGq0aLRmvGSadt0i2bdLwmXSuLSfRvKWklaSFpHTnppkw6IpOuxqQzYYGJOVleWl1aXFpbTlbMk1XvZOU6WX1adFJzWnJacVpwWm/OcDCCKa0m6c5ClDrUMtQq1CLUGnT6FMWFYKpIi1Pv4DtWpham1qWT6mZSocwlO4LxKJHwJ6tVi1Vr1UkGm2ShSSaZWzkIPvwimMg6iY6TCDeJUpNIM4kWE4+feK1TgudZGlsZWxhPPG/ieRPPs2S2YmZqrZMtk62SLZIXnrfwvIXnLTzP6hlVWTtbOls5WzgvPG/heQvPW3ieFTWqt562nLaatpheeN7C8xaet/A8q2xMyRrbEtsK2wJ74XkLz1t43sLzrLwxTetuy26rbovuFQ5GMJ638DyrcUzdWtxS3ErcQnzheWvKhWD8wQod17E+tzy3Orc4X76ej1PsCMbzvIDnWbJbsVuwLzxv4XkLz1tbOQg+/CIYz1t43sLzFp638LyF5y08b+F5Pjme5/rA5YGrg4XnLTxv4XmuG1w2MAMuFlwruFRwpbDxvI3nbTxv43kuIZhRFxCuH1w+uHrYeN7G8zaet/E8lxVoyEWFawqXFK4oNp638byN5208z6UGGneh4TrDZYarjI3nbTxv43kbz3P5gQW5+HDt4dLDlccOByMYz9t4nksSLNIFiesRlyOuRjaet6dcCMbzXKZg4S5SXKO4RHGFsvG8jeftJTuCsV88xoWL6xaXLa5atvPme/pcJQfBh18E43kbz9t43sbzNp638byN5208TwA8z0WSaySXSBvP23jexvNcPLl24kFdMZ2fP1STcriXmsNaXXNYl3BYd1h32JBw2HDYcFhIOCwcFg6bEg6bDpsOWxIOWw5bDtsSDtsO2w47Eg47DjsOK8Jh6TC1wRUn17klXLnuPISrQ7g6hKtDuHJp6soUM3Rd6rLUVamL0kPcOsStQ9w6xC3XrS5bsW8Xra5ZXbK6Yj0EsEMAOwSwQwBzKYu/uJB1Hesy1lXsCQcjmAB2CGAub/E/F7eubV3aurI9BLAz5UIwAcwlL/7sgvdYWh5ry2NxeSwYXRcfS8ZjzXgsGo+FoMvnYyl4rAWPxeCxwHOVfSzxjjXescg7Fm6HAHss3Y6127F4OxZkh0B8LMmONdmxKDurZsvpqvmqiag31EUJ7McS6lhDHYuoY2F0ilMvtIQ51jDHuoQ4bLPBXoOtBjsNh0RxSBSHRHG2cvAWH4kLRg9jgK6qR+kBWqwW5pOWQBD8BcE39oVJHXY3GJs/Eg2iQwyIgJgQC2JDHAgQkIeBZ/MKCIS6JNQloS4JdUmoS0Jd4hO8XeIRiUNk9xYIhLok1CWhLgl1SahLnIhpS1wo8aDEgXI4BgRCXRLqklCX9O8SryOVJz6XuFzicUnMy3AwCMS8JOYlzb3ETakREidNfDRx0ST4JcEvWdwnzkuFkbhu4rmJ4ybrksQN+d//xL0S90rcK3GvxHUoYT5TfT4LfT4DfShMHuqSh8OVz4+/DOkM6d4aEAExIRbEhjgQPAzcMMML6wJ5gbxAXvAumJfcsgO4AORRNoI3gjeCN4I3gjeCN4K3ckDYIHDhgHBAOCAcx8DkL0wJU8KUPFbyWMljJY+VCEbbKJdDkQ9nIh+ORD6cfnzQP+r/wsnDCcSHA4gP5w8fjh8+fHLg4ZMDD+cRH44jPo0hjFj8Ih8lcyDw4ezf84Wth5N/Dwf/Hs79PRz7e/gX/4fjfw+n/57GBZTDv/g//Iv/SzgGpu8XL8AJOK73cFrv4bDewwm9p8vMncEvzMwTDoT/4D54D86D73CU7OEk2cNBsodzZA//OfHwnxMP/znxcMLs4YDZwxNxrOzhVNnDobJ/hPd63ay7QyqkjpRADvMetxDK3HIo7eFM2sORtId/sng4mvZwMu3BPrFKzoI9HAV7OAn28P8JD+fAHiz4yzfPl24eFIU9fznmQTaikYzgL708HGd5OK/wfPnmAZkBX0p5vozyfAnl+fLJQx/+4WzH81XXz1SEMhSilCkTuItfuAmc9L2fr1h/5OU6VkhX+aFR/CCMmvzhjMNDHf4QuonclL4Ple9DKF9KI0h81exDMftQyz48PA29h4bew9vAQsggYhDoifOEeQIJcQTBtAEeFvoPS/mHle7DWvbhIb769PnK0+erTp+vOH2+2vQhEBGHmGkmGm/H2fH1z5/v92z3e7T7Pdn9vO9+Sfd+Sfd+Sfd+D36/576f+i455JJDLjnkNi44tq4cCMTBM/iFZ8Az4BnwfI/6pY7LUfTLSfTLQfTLOfTLd2cu3525HEy/nEu/Xwq6X3q5Pux3/4t2l+Pd10+uXD+5cv3kyj9qSIXUlDpSAiDEX+Q3ryCdp+s+HndAZQY5q339esH16wXXrxf8o+TsyBxeGrKW3BL8ZxysvDIvjJb8f/Pr/5tf/9/8+v/m1/83vxz2vpz1vhzwvpzvvl+CvJzuvv7H9PU/pq//MX39j+nrf0xfjoNf/2P6+t/RlxPilwPil/Phl+Ph90vOl8Phl9Pft/P7jWQymUomkmn8UtX9ss/9ss/9ss/FJ5jsLwXcL/vcL/vcL/vcL/vcL/vcL9fcb2lzOXJ0OTZ0OfpzOdd5OW5ygwvf3ygWLaEkfA/X+7LGRXeoDo0x/cw0E/3lhfvlhftlgfvF/EvMv8T8S/viclTr0sa4KA2dwcvuyWX35LJ7cpHKPshlH+SyD3I5O3XZ47g8wZdMLhsGlw2Dy4bBZcPgsitwv8xzv8xzv8xzeRta5JcW+aVFfmmRv4SDkfr9wgwvDdNLw/TSML30QC890AsOPdBLD/TSA730QC890EsP9NLxvHQ8L497GMpIo8QxShyjxOEUxz9Kzp/iXVJb6kiBzShDhZ3Fa2fxHzWkQmpKlZQtdaTA4p6GdrS0o6mdLdYWa4u1xdo/Je9IgcWVI9YR64h1xDpiHbGOWEes81OSwfJXrBQrxUqxUqwUK8VKsVIs2l73q3ne35+imlSXGlIhNaWW1JY6UmAh10InrXTSUiebWE2sJlYTq4nVxGpiIQ2fSkuMtCbI/lPDhlRITakltaWOlKAKboK1uiZYE6wJ1gRrgjXBmmBNMMXVO9YD/LkrWBesC9YF64J1wbpgXjqCHcGOYEewI9gR7Ah2BDslWbAiBNN4eqk2BUvBUrAULAVLwSjilTG0j6F9DO1j/NS4kJpSS2pLHSmwGE9az6mdzFbXutSQCqkSsqS21JESVHHaydROZq+7gmknUzuZ2snUTqZGMdXYVMgQbAg2BBs1TrAh2BBsCDYEG4LJGoKFYCFYCBbFIVgIFoKFYCFYEYJplFOjnBrU1ChnKV6jnBrl1CinRskos2iaRdMsmmbRNIumWTTNomkWTbNomkV9DrNomkXTLJpm0TSLplk0zaJpFk2zaJpFfVOzaJpF0yyaZtE0i6ZZNM2iaRZNs2iaRZ1L1WU6TdNpmk7TdJqm0zSdpuk0TadpOs1Kp1pE6tnZ6ppgenbq2alnp56denbq2alna3SV5SoFVX5IPTv17NSzU89OPbvCfcVi7Tr17NSzU8/OUeME07NTz049O/Xs1LM1lDTdpOkmTTdpuknTTZpu0nSTpps8JVmwIgQrPdYk1wzo2alnpz6betSf1/gwfj8T/PVD3L9+iPvXD3H/+iHuXz/E/euHuH/9EPevH+L+9UPcv36I+1e5Taz251qXGlIhNaWW1JY6UmAhrYvVxep/7g6pkJpSS2pLHSmxFNwEa3VNsCZYE6wJ1gRrgjXBmmCK64LVA/y5K1gXrAvWBeuCdcG6YAoZgg3BhmCjxgk2BBuCDcGGYEMwLx3BjmBHsCPYEewIdgQ7gp2SLFgRgqVgKVgKloKlYClYCpaC6WTIcBLHT1FNqksVQ0hNqSW1pY6UoArWKkera4JplUOrHFrl0CqHVjm0yqFVagpDqxxa5eh1VzCtcmiVQ6scWuXQKoYq09pGTWi9bT3Kn3GCaZVDqxxa5dAqh1ZZrCFYCBaChWBRHIKFYCFYCBaCyTAFm4JNwaZgU7BZvIJNwaZgUzAv6W9Dfxv629Dfhv429Lehvw39bZySLFgRgulvQ38b+tvQ34b+NvS3ob8N/W3ob3CGbha6WehmoZvFH44ptaS21JECi/FTrCnWFGuKNcWaf3iX1JY6UmAxaom1xFpiLbGWWEus9UfKljpSYHFvi7XF2mJtsbZYW6wt1v4j70iBxZUj1hHriHXEOmIdsY5YR6zzRzJY/oqVYqVYKVaKlWKlWClWikX1/UvcJeoSc4m4xFuiLbGWSMvhh18OP/xy+OGXow6/HHX4JSgTkonDRGFrE0sTKxPLDKsMAjZBmg/6/PI9n18+5/PL15F/+ZjPL/GcaE4sJ5Kb3s3uJndzuynbjE30J+QT8M1uJjdzm4nKPEVuMEuZpMxRpigzlAnKXGQqIsOQJIjfhu9hMBgGg2EwGAaDYTAYuruR38Bv3DfsG/UN+sZ88hvfpfnlszS/fJXml4/S/PIJxH+Eg8JRUcNq3JTieZeXhPZZmLl/mzL/+38=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"ICD10 Code" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ICD10 Code", type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "ICD10 Code", "ICD10 Code - Copy"),
				    #"Split Column by Position" = Table.SplitColumn(#"Duplicated Column", "ICD10 Code - Copy", Splitter.SplitTextByPositions({0, 3}, false), {"ICD10 Code.1", "ICD10 Code.2"}),
				    #"Added Custom" = Table.AddColumn(#"Split Column by Position", "Custom", each if Text.Length([ICD10 Code.2])=1 then Text.PadStart([ICD10 Code.2],2,"0") else [ICD10 Code.2], type text),
				    #"Merged Columns" = Table.CombineColumns(#"Added Custom",{"ICD10 Code.1", "Custom"},Combiner.CombineTextByDelimiter(".", QuoteStyle.None),"lookup_cause_code")
				in
				    #"Merged Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

