table DIM_AGE
	lineageTag: bbda7cb2-f964-4241-817d-d7bd147de2cf

	column age
		dataType: int64
		formatString: 0
		lineageTag: f95765d2-e9f6-40d6-a7ad-363623195704
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column age_5y
		dataType: string
		lineageTag: 24148776-8f16-42ed-93f7-f6defd77ac8d
		summarizeBy: none
		sourceColumn: age_5y
		sortByColumn: order_age_5y

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column order_age_5y
		dataType: int64
		formatString: 0
		lineageTag: 51f8c37a-e566-4730-b17d-607eebf2829b
		summarizeBy: sum
		sourceColumn: order_age_5y

		annotation SummarizationSetBy = Automatic

	column age_10y
		dataType: string
		lineageTag: ee47d7e7-579d-4b01-9fcf-4944c1e571ed
		summarizeBy: none
		sourceColumn: age_10y
		sortByColumn: order_age_10y

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column order_age_10y
		dataType: int64
		formatString: 0
		lineageTag: 2b544bdf-440e-4da5-9934-6d848741eb45
		summarizeBy: sum
		sourceColumn: order_age_10y

		annotation SummarizationSetBy = Automatic

	column adult_child
		dataType: string
		lineageTag: d2336203-ce9f-415c-b5ba-cdf38bfb21ff
		summarizeBy: none
		sourceColumn: adult_child
		sortByColumn: order_adult_child

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column order_adult_child
		dataType: int64
		formatString: 0
		lineageTag: 2f2cf633-8544-4acd-83f6-a705e3943bcc
		summarizeBy: sum
		sourceColumn: order_adult_child

		annotation SummarizationSetBy = Automatic

	partition DIM_AGE-1d014bf9-f538-4643-af6d-d5129c2b25b5 = m
		mode: import
		queryGroup: Dimension
		source =
				let
				    Source = {0..130},
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(),type table [age= Int64.Type], null, ExtraValues.Error),
				    #"Inserted Integer-Division" = Table.AddColumn(#"Converted to Table", "age 5y", each Number.IntegerDivide([age], 5)*5, Int64.Type),
				    #"Inserted Addition" = Table.AddColumn(#"Inserted Integer-Division", "Addition", each [age 5y] + 4, Int64.Type),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Inserted Addition", "age 5y", "order_age_5y"),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column", {{"age 5y", type text}, {"Addition", type text}}, "en-AU"),{"age 5y", "Addition"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"age_5y"),
				    #"Inserted Integer-Division1" = Table.AddColumn(#"Merged Columns", "_age_10y", each Number.IntegerDivide([age], 10)*10, Int64.Type),
				    #"Inserted Addition1" = Table.AddColumn(#"Inserted Integer-Division1", "Addition", each [_age_10y] + 9, Int64.Type),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Inserted Addition1", "_age_10y", "order_age_10y"),
				    #"Merged Columns1" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"_age_10y", type text}, {"Addition", type text}}, "en-AU"),{"_age_10y", "Addition"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"age_10y"),
				    #"Replaced Value" = Table.ReplaceValue(#"Merged Columns1",each [age] >=80,"80+",(x,y,z) as text=> if y then z else x,{"age_5y", "age_10y"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",each [age]>=80,80,(x,y,z) as number=> if y then z else x,{"order_age_5y","order_age_10y"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value1",{{"order_age_5y", Int64.Type}, {"order_age_10y", Int64.Type}}),
				    Custom1 = Table.InsertRows( #"Changed Type",  0, {[age=-1, age_5y="NA", order_age_5y = -1, age_10y="NA",order_age_10y=-1,order_age_80=-1 ]}),
				    #"Added Custom" = Table.AddColumn(Custom1, "adult_child", each if [age]>14 then "Adult 15+" else "Child <15", type text),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "order_adult_child",  each if [age]>14 then 2 else 1, Int64.Type)
				in
				    #"Added Custom1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

