table DIM_INJURY_CAUSE
	lineageTag: 3c833ef7-1be0-48bb-86e0-9c202ea3e667

	column cause_icd_code_id
		dataType: string
		lineageTag: 3a8144e7-8af2-4a80-a661-98a0018186e5
		summarizeBy: none
		sourceColumn: cause_icd_code_id

		annotation SummarizationSetBy = Automatic

	column 'ICD-10 code descriptor'
		dataType: string
		lineageTag: 153146f0-583a-4e5f-bbcb-f254babd2190
		summarizeBy: none
		sourceColumn: ICD-10 code descriptor

		annotation SummarizationSetBy = Automatic

	column 'ICD-10 Map'
		dataType: string
		lineageTag: ddeba42e-0e24-4adb-a29e-630df5c0afdd
		summarizeBy: none
		sourceColumn: ICD-10 Map

		annotation SummarizationSetBy = Automatic

	column Cause
		dataType: string
		lineageTag: 2dfa2639-1a5a-4f2d-a2b2-878fb3240112
		summarizeBy: none
		sourceColumn: Cause

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column cause_order
		dataType: int64
		formatString: 0
		lineageTag: 93fb2a52-fc52-47c8-b0ce-aaf81f03d20e
		summarizeBy: none
		sourceColumn: cause_order

		annotation SummarizationSetBy = Automatic

	column Transport
		dataType: string
		lineageTag: 7be07030-6433-4c9f-aef5-5718fcc4b7d9
		summarizeBy: none
		sourceColumn: Transport

		annotation SummarizationSetBy = Automatic

	column 'Transport - order'
		dataType: string
		lineageTag: e7d2494c-1974-4b12-8b1e-264602abe123
		summarizeBy: none
		sourceColumn: Transport - order

		annotation SummarizationSetBy = Automatic

	hierarchy 'Transport Hierarchy'
		lineageTag: b0012c44-0424-4bcb-aa9f-68ee769ebb42

		level Transport
			lineageTag: 01479165-d072-4274-9dd4-6836d5a4ce16
			column: Transport

		level Cause
			lineageTag: d115e91a-436a-46c0-bd60-93437a2f65b6
			column: Cause

	partition DIM_INJURY_CAUSE-58cbba83-91ef-4dc9-b388-76564cf898f9 = m
		mode: import
		queryGroup: Dimension
		source = ```
				let
				    Source = injury_cause,
				    
				    assault_list = {
				        "X86.07",
				        "X89.08",
				        "X91",
				        "X91.00",
				        "X91.01",
				        "X91.03",
				        "X91.04",
				        "X91.08",
				        "X91.09",
				        "X91.1",
				        "X92.01",
				        "X93",
				        "X93.00",
				        "X93.05",
				        "X93.08",
				        "X93.09",
				        "X95",
				        "X95.08",
				        "X95.09",
				        "X95.14",
				        "X95.17",
				        "X95.19",
				        "X95.2",
				        "X95.20",
				        "X95.22",
				        "X95.24",
				        "X95.26",
				        "X95.27",
				        "X95.28",
				        "X95.29",
				        "X95.37",
				        "X95.39",
				        "X95.42",
				        "X95.48",
				        "X95.81",
				        "X95.89",
				        "X95.9",
				        "X95.91",
				        "X95.92",
				        "X95.94",
				        "X95.95",
				        "X95.96",
				        "X95.97",
				        "X95.98",
				        "X95.99",
				        "X97.00",
				        "X97.01",
				        "X97.04",
				        "X97.08",
				        "X97.09",
				        "X98.09",
				        "X99",
				        "X99.0",
				        "X99.00",
				        "X99.01",
				        "X99.02",
				        "X99.04",
				        "X99.06",
				        "X99.07",
				        "X99.08",
				        "X99.09",
				        "X99.1",
				        "X99.16",
				        "X99.28",
				        "X99.30",
				        "X99.32",
				        "X99.34",
				        "X99.36",
				        "X99.37",
				        "X99.39",
				        "X99.4",
				        "X99.48",
				        "X99.49",
				        "X99.58",
				        "X99.8",
				        "X99.80",
				        "X99.81",
				        "X99.82",
				        "X99.84",
				        "X99.86",
				        "X99.87",
				        "X99.88",
				        "X99.89",
				        "X99.9",
				        "X99.90",
				        "X99.92",
				        "X99.94",
				        "X99.96",
				        "X99.97",
				        "X99.98",
				        "X99.99",
				        "Y00",
				        "Y00.00",
				        "Y00.01",
				        "Y00.02",
				        "Y00.03",
				        "Y00.04",
				        "Y00.05",
				        "Y00.06",
				        "Y00.07",
				        "Y00.08",
				        "Y00.09",
				        "Y00.18",
				        "Y00.41",
				        "Y00.48",
				        "Y00.49",
				        "Y00.51",
				        "Y00.59",
				        "Y00.88",
				        "Y00.89",
				        "Y01",
				        "Y01.00",
				        "Y01.02",
				        "Y01.04",
				        "Y01.06",
				        "Y01.07",
				        "Y01.08",
				        "Y01.09",
				        "Y02.34",
				        "Y02.36",
				        "Y02.39",
				        "Y02.90",
				        "Y03.00",
				        "Y03.09",
				        "Y03.20",
				        "Y03.28",
				        "Y03.29",
				        "Y03.37",
				        "Y03.48",
				        "Y03.49",
				        "Y03.59",
				        "Y03.80",
				        "Y03.82",
				        "Y03.86",
				        "Y03.88",
				        "Y03.89",
				        "Y04",
				        "Y04.00",
				        "Y04.01",
				        "Y04.02",
				        "Y04.03",
				        "Y04.04",
				        "Y04.05",
				        "Y04.06",
				        "Y04.07",
				        "Y04.08",
				        "Y04.09",
				        "Y04.18",
				        "Y04.19",
				        "Y04.29",
				        "Y04.41",
				        "Y04.48",
				        "Y04.49",
				        "Y04.58",
				        "Y04.59",
				        "Y04.8",
				        "Y04.80",
				        "Y04.88",
				        "Y04.89",
				        "Y05.04",
				        "Y05.06",
				        "Y05.08",
				        "Y06.01",
				        "Y07",
				        "Y07.0",
				        "Y07.01",
				        "Y07.04",
				        "Y07.08",
				        "Y07.09",
				        "Y07.8",
				        "Y08",
				        "Y08.00",
				        "Y08.01",
				        "Y08.03",
				        "Y08.04",
				        "Y08.06",
				        "Y08.07",
				        "Y08.08",
				        "Y08.09",
				        "Y08.48",
				        "Y09",
				        "Y09.00",
				        "Y09.01",
				        "Y09.02",
				        "Y09.04",
				        "Y09.05",
				        "Y09.06",
				        "Y09.07",
				        "Y09.08",
				        "Y09.09",
				        "Y09.9",
				        "Y09.99"
				    },
				    high_fall_list = {
				        "W09",
				        "W09.0",
				        "W09.08",
				        "W09.1",
				        "W09.2",
				        "W09.3",
				        "W09.4",
				        "W09.40",
				        "W09.5",
				        "W09.6",
				        "W09.60",
				        "W09.8",
				        "W09.9",
				        "W10",
				        "W10.0",
				        "W10.01",
				        "W10.03",
				        "W10.08",
				        "W10.09",
				        "W10.1",
				        "W10.2",
				        "W10.21",
				        "W10.48",
				        "W10.5",
				        "W10.58",
				        "W10.59",
				        "W10.62",
				        "W10.8",
				        "W10.88",
				        "W10.9",
				        "W11",
				        "W11.03",
				        "W11.04",
				        "W11.08",
				        "W11.09",
				        "W11.13",
				        "W11.52",
				        "W11.53",
				        "W11.59",
				        "W11.62",
				        "W11.72",
				        "W11.74",
				        "W12",
				        "W12.08",
				        "W12.52",
				        "W13",
				        "W13.0",
				        "W13.03",
				        "W13.08",
				        "W13.1",
				        "W13.2",
				        "W13.3",
				        "W13.30",
				        "W13.4",
				        "W13.5",
				        "W13.58",
				        "W13.62",
				        "W13.7",
				        "W13.73",
				        "W13.8",
				        "W13.80",
				        "W13.88",
				        "W13.9",
				        "W14",
				        "W14.01",
				        "W14.03",
				        "W14.08",
				        "W14.82",
				        "W14.88",
				        "W14.89",
				        "W15",
				        "W15.30",
				        "W15.81",
				        "W15.88",
				        "W16",
				        "W16.0",
				        "W16.08",
				        "W16.1",
				        "W16.2",
				        "W16.6",
				        "W16.8",
				        "W16.83",
				        "W16.88",
				        "W16.9",
				        "W17",
				        "W17.0",
				        "W17.02",
				        "W17.03",
				        "W17.08",
				        "W17.1",
				        "W17.2",
				        "W17.3",
				        "W17.4",
				        "W17.48",
				        "W17.5",
				        "W17.52",
				        "W17.58",
				        "W17.6",
				        "W17.68",
				        "W17.7",
				        "W17.8",
				        "W17.80",
				        "W17.81",
				        "W17.89",
				        "W17.9",
				        "X80",
				        "X80.08",
				        "X80.58",
				        "X80.88",
				        "X80.89",
				        "Y30"
				    },
				    low_fall_list = {
				        "W00",
				        "W00.08",
				        "W00.2",
				        "W00.80",
				        "W01",
				        "W01.0",
				        "W01.00",
				        "W01.01",
				        "W01.02",
				        "W01.04",
				        "W01.08",
				        "W01.09",
				        "W01.1",
				        "W01.10",
				        "W01.14",
				        "W01.18",
				        "W01.19",
				        "W01.2",
				        "W01.24",
				        "W01.28",
				        "W01.3",
				        "W01.30",
				        "W01.31",
				        "W01.39",
				        "W01.4",
				        "W01.40",
				        "W01.41",
				        "W01.48",
				        "W01.49",
				        "W01.5",
				        "W01.52",
				        "W01.54",
				        "W01.58",
				        "W01.59",
				        "W01.72",
				        "W01.8",
				        "W01.88",
				        "W01.89",
				        "W01.9",
				        "W02",
				        "W02.0",
				        "W02.01",
				        "W02.1",
				        "W02.2",
				        "W02.3",
				        "W02.4",
				        "W02.41",
				        "W02.5",
				        "W02.6",
				        "W02.60",
				        "W02.7",
				        "W02.8",
				        "W02.81",
				        "W02.88",
				        "W02.9",
				        "W02.90",
				        "W03",
				        "W04",
				        "W04.00",
				        "W04.04",
				        "W04.08",
				        "W04.09",
				        "W04.14",
				        "W04.48",
				        "W04.49",
				        "W05",
				        "W06",
				        "W06.0",
				        "W06.04",
				        "W06.08",
				        "W06.09",
				        "W06.1",
				        "W06.14",
				        "W06.18",
				        "W06.2",
				        "W06.20",
				        "W06.3",
				        "W06.5",
				        "W06.6",
				        "W06.60",
				        "W06.8",
				        "W06.9",
				        "W07",
				        "W07.0",
				        "W07.08",
				        "W07.1",
				        "W07.14",
				        "W07.2",
				        "W07.3",
				        "W07.4",
				        "W07.5",
				        "W07.6",
				        "W07.7",
				        "W07.8",
				        "W07.9",
				        "W08",
				        "W08.0",
				        "W08.04",
				        "W08.08",
				        "W08.1",
				        "W08.2",
				        "W08.29",
				        "W08.8",
				        "W08.9",
				        "W18",
				        "W18.0",
				        "W18.03",
				        "W18.08",
				        "W18.1",
				        "W18.12",
				        "W18.2",
				        "W18.4",
				        "W18.6",
				        "W18.62",
				        "W18.8",
				        "W18.88",
				        "W18.9",
				        "W18.92",
				        "W19",
				        "W19.0",
				        "W19.01",
				        "W19.03",
				        "W19.04",
				        "W19.08",
				        "W19.09",
				        "W19.18",
				        "W19.19",
				        "W19.3",
				        "W19.43",
				        "W19.48",
				        "W19.59",
				        "W19.62",
				        "W19.72",
				        "W19.82",
				        "W19.89",
				        "W19.99"
				    },
				    motor_vehical_list = {
				        "V40.00",
				        "V40.08",
				        "V40.10",
				        "V40.19",
				        "V40.20",
				        "V40.29",
				        "V40.30",
				        "V40.32",
				        "V40.40",
				        "V40.5",
				        "V40.51",
				        "V40.58",
				        "V40.59",
				        "V40.61",
				        "V40.68",
				        "V40.69",
				        "V40.78",
				        "V40.79",
				        "V41.51",
				        "V41.59",
				        "V42.51",
				        "V42.59",
				        "V42.60",
				        "V42.61",
				        "V42.69",
				        "V43",
				        "V43.00",
				        "V43.01",
				        "V43.03",
				        "V43.08",
				        "V43.09",
				        "V43.10",
				        "V43.18",
				        "V43.19",
				        "V43.20",
				        "V43.21",
				        "V43.28",
				        "V43.29",
				        "V43.39",
				        "V43.40",
				        "V43.41",
				        "V43.42",
				        "V43.43",
				        "V43.48",
				        "V43.49",
				        "V43.5",
				        "V43.50",
				        "V43.51",
				        "V43.52",
				        "V43.53",
				        "V43.58",
				        "V43.59",
				        "V43.6",
				        "V43.60",
				        "V43.61",
				        "V43.62",
				        "V43.63",
				        "V43.68",
				        "V43.69",
				        "V43.70",
				        "V43.71",
				        "V43.78",
				        "V43.79",
				        "V43.9",
				        "V43.90",
				        "V43.92",
				        "V43.98",
				        "V43.99",
				        "V44",
				        "V44.00",
				        "V44.03",
				        "V44.08",
				        "V44.09",
				        "V44.20",
				        "V44.48",
				        "V44.5",
				        "V44.50",
				        "V44.51",
				        "V44.52",
				        "V44.53",
				        "V44.58",
				        "V44.59",
				        "V44.6",
				        "V44.60",
				        "V44.61",
				        "V44.63",
				        "V44.68",
				        "V44.69",
				        "V44.99",
				        "V45.00",
				        "V45.50",
				        "V45.51",
				        "V45.58",
				        "V45.59",
				        "V45.60",
				        "V45.61",
				        "V45.69",
				        "V46.09",
				        "V46.50",
				        "V46.51",
				        "V46.52",
				        "V46.59",
				        "V46.60",
				        "V46.61",
				        "V46.69",
				        "V46.71",
				        "V46.78",
				        "V46.99",
				        "V47",
				        "V47.0",
				        "V47.00",
				        "V47.01",
				        "V47.02",
				        "V47.08",
				        "V47.09",
				        "V47.1",
				        "V47.10",
				        "V47.11",
				        "V47.18",
				        "V47.19",
				        "V47.2",
				        "V47.20",
				        "V47.29",
				        "V47.39",
				        "V47.40",
				        "V47.41",
				        "V47.43",
				        "V47.48",
				        "V47.5",
				        "V47.50",
				        "V47.51",
				        "V47.52",
				        "V47.53",
				        "V47.58",
				        "V47.59",
				        "V47.6",
				        "V47.60",
				        "V47.61",
				        "V47.62",
				        "V47.63",
				        "V47.68",
				        "V47.69",
				        "V47.70",
				        "V47.78",
				        "V47.79",
				        "V47.9",
				        "V47.90",
				        "V47.92",
				        "V47.99",
				        "V48",
				        "V48.00",
				        "V48.01",
				        "V48.02",
				        "V48.08",
				        "V48.09",
				        "V48.1",
				        "V48.10",
				        "V48.11",
				        "V48.18",
				        "V48.19",
				        "V48.2",
				        "V48.21",
				        "V48.28",
				        "V48.29",
				        "V48.30",
				        "V48.32",
				        "V48.38",
				        "V48.39",
				        "V48.4",
				        "V48.40",
				        "V48.41",
				        "V48.43",
				        "V48.48",
				        "V48.49",
				        "V48.5",
				        "V48.50",
				        "V48.51",
				        "V48.52",
				        "V48.53",
				        "V48.54",
				        "V48.58",
				        "V48.59",
				        "V48.6",
				        "V48.60",
				        "V48.61",
				        "V48.62",
				        "V48.63",
				        "V48.68",
				        "V48.69",
				        "V48.7",
				        "V48.70",
				        "V48.71",
				        "V48.78",
				        "V48.79",
				        "V48.9",
				        "V48.90",
				        "V48.91",
				        "V48.99",
				        "V49",
				        "V49.0",
				        "V49.1",
				        "V49.18",
				        "V49.2",
				        "V49.3",
				        "V49.4",
				        "V49.40",
				        "V49.5",
				        "V49.59",
				        "V49.6",
				        "V49.69",
				        "V49.8",
				        "V49.81",
				        "V49.9",
				        "V50.6",
				        "V53.0",
				        "V53.2",
				        "V53.4",
				        "V53.5",
				        "V53.6",
				        "V53.7",
				        "V53.9",
				        "V54.0",
				        "V54.4",
				        "V54.5",
				        "V54.6",
				        "V55.5",
				        "V56.0",
				        "V57.0",
				        "V57.1",
				        "V57.2",
				        "V57.4",
				        "V57.5",
				        "V57.6",
				        "V57.7",
				        "V57.9",
				        "V58.0",
				        "V58.1",
				        "V58.2",
				        "V58.4",
				        "V58.48",
				        "V58.5",
				        "V58.6",
				        "V58.7",
				        "V58.9",
				        "V59.0",
				        "V59.1",
				        "V59.4",
				        "V59.6",
				        "V59.8",
				        "V59.9",
				        "V60.0",
				        "V60.2",
				        "V63.0",
				        "V63.4",
				        "V63.5",
				        "V63.51",
				        "V63.6",
				        "V63.7",
				        "V63.9",
				        "V64.4",
				        "V64.5",
				        "V64.6",
				        "V64.7",
				        "V64.9",
				        "V65.3",
				        "V66.3",
				        "V66.5",
				        "V66.9",
				        "V67.0",
				        "V67.2",
				        "V67.5",
				        "V67.6",
				        "V67.9",
				        "V68",
				        "V68.0",
				        "V68.1",
				        "V68.2",
				        "V68.4",
				        "V68.42",
				        "V68.5",
				        "V68.51",
				        "V68.6",
				        "V68.61",
				        "V68.7",
				        "V68.9",
				        "V69.0",
				        "V69.1",
				        "V69.3",
				        "V69.32",
				        "V69.4",
				        "V69.8",
				        "V69.9",
				        "V70.6",
				        "V73.4",
				        "V73.5",
				        "V73.6",
				        "V74.5",
				        "V74.6",
				        "V77.5",
				        "V77.6",
				        "V78.0",
				        "V78.1",
				        "V78.4",
				        "V78.5",
				        "V78.6",
				        "V78.7",
				        "V79.1",
				        "V79.3",
				        "V79.5",
				        "V79.8",
				        "V79.9"
				    },
				    motorcycle_list = {
				        "V20.00",
				        "V20.01",
				        "V20.02",
				        "V20.08",
				        "V20.09",
				        "V20.22",
				        "V20.31",
				        "V20.4",
				        "V20.40",
				        "V20.41",
				        "V20.42",
				        "V20.48",
				        "V20.49",
				        "V20.51",
				        "V20.52",
				        "V20.59",
				        "V20.92",
				        "V20.99",
				        "V21.40",
				        "V21.49",
				        "V21.91",
				        "V22.0",
				        "V22.00",
				        "V22.01",
				        "V22.02",
				        "V22.08",
				        "V22.09",
				        "V22.11",
				        "V22.18",
				        "V22.19",
				        "V22.22",
				        "V22.4",
				        "V22.40",
				        "V22.41",
				        "V22.42",
				        "V22.43",
				        "V22.48",
				        "V22.49",
				        "V22.51",
				        "V22.58",
				        "V22.59",
				        "V22.91",
				        "V22.92",
				        "V22.99",
				        "V23",
				        "V23.0",
				        "V23.00",
				        "V23.01",
				        "V23.02",
				        "V23.08",
				        "V23.09",
				        "V23.11",
				        "V23.12",
				        "V23.20",
				        "V23.21",
				        "V23.4",
				        "V23.40",
				        "V23.41",
				        "V23.42",
				        "V23.48",
				        "V23.49",
				        "V23.5",
				        "V23.50",
				        "V23.51",
				        "V23.52",
				        "V23.58",
				        "V23.59",
				        "V23.90",
				        "V23.91",
				        "V23.92",
				        "V23.98",
				        "V23.99",
				        "V24.00",
				        "V24.02",
				        "V24.08",
				        "V24.11",
				        "V24.29",
				        "V24.4",
				        "V24.40",
				        "V24.41",
				        "V24.48",
				        "V24.49",
				        "V24.51",
				        "V24.90",
				        "V24.99",
				        "V25.40",
				        "V25.41",
				        "V25.48",
				        "V26.00",
				        "V26.01",
				        "V26.02",
				        "V26.08",
				        "V26.09",
				        "V26.19",
				        "V26.29",
				        "V26.39",
				        "V26.41",
				        "V26.49",
				        "V26.59",
				        "V26.90",
				        "V26.99",
				        "V27",
				        "V27.0",
				        "V27.00",
				        "V27.01",
				        "V27.02",
				        "V27.08",
				        "V27.09",
				        "V27.1",
				        "V27.12",
				        "V27.18",
				        "V27.19",
				        "V27.20",
				        "V27.22",
				        "V27.29",
				        "V27.30",
				        "V27.39",
				        "V27.4",
				        "V27.40",
				        "V27.41",
				        "V27.42",
				        "V27.44",
				        "V27.48",
				        "V27.49",
				        "V27.5",
				        "V27.50",
				        "V27.51",
				        "V27.58",
				        "V27.59",
				        "V27.90",
				        "V27.91",
				        "V27.92",
				        "V27.98",
				        "V27.99",
				        "V28",
				        "V28.0",
				        "V28.00",
				        "V28.01",
				        "V28.02",
				        "V28.08",
				        "V28.09",
				        "V28.10",
				        "V28.11",
				        "V28.12",
				        "V28.18",
				        "V28.21",
				        "V28.22",
				        "V28.29",
				        "V28.30",
				        "V28.32",
				        "V28.4",
				        "V28.40",
				        "V28.41",
				        "V28.42",
				        "V28.48",
				        "V28.49",
				        "V28.5",
				        "V28.50",
				        "V28.51",
				        "V28.52",
				        "V28.58",
				        "V28.59",
				        "V28.90",
				        "V28.91",
				        "V28.92",
				        "V28.98",
				        "V28.99",
				        "V29",
				        "V29.0",
				        "V29.00",
				        "V29.01",
				        "V29.08",
				        "V29.1",
				        "V29.2",
				        "V29.3",
				        "V29.30",
				        "V29.38",
				        "V29.4",
				        "V29.49",
				        "V29.5",
				        "V29.6",
				        "V29.8",
				        "V29.81",
				        "V29.9",
				        "V29.90",
				        "V30.11",
				        "V30.5",
				        "V31.0",
				        "V32.1",
				        "V32.5",
				        "V32.6",
				        "V32.9",
				        "V33.0",
				        "V33.1",
				        "V33.5",
				        "V33.6",
				        "V33.7",
				        "V33.9",
				        "V37.0",
				        "V37.1",
				        "V37.2",
				        "V37.3",
				        "V37.41",
				        "V37.6",
				        "V37.7",
				        "V37.9",
				        "V38.0",
				        "V38.4",
				        "V38.41",
				        "V38.5",
				        "V38.6",
				        "V38.71",
				        "V38.9",
				        "V39.0",
				        "V39.3",
				        "V39.4",
				        "V39.8",
				        "V39.9",
				        "V86",
				        "V86.00",
				        "V86.01",
				        "V86.02",
				        "V86.08",
				        "V86.09",
				        "V86.12",
				        "V86.14",
				        "V86.18",
				        "V86.2",
				        "V86.39",
				        "V86.40",
				        "V86.41",
				        "V86.42",
				        "V86.5",
				        "V86.50",
				        "V86.51",
				        "V86.52",
				        "V86.53",
				        "V86.58",
				        "V86.59",
				        "V86.62",
				        "V86.69",
				        "V86.7",
				        "V86.70",
				        "V86.71",
				        "V86.72",
				        "V86.91",
				        "V86.92",
				        "V86.99"
				    },
				    pedal_cyclist_list = {
				        "V10",
				        "V10.0",
				        "V10.1",
				        "V10.2",
				        "V10.4",
				        "V10.41",
				        "V10.5",
				        "V10.9",
				        "V11",
				        "V11.0",
				        "V11.2",
				        "V11.4",
				        "V11.41",
				        "V11.9",
				        "V12.0",
				        "V12.4",
				        "V12.41",
				        "V12.5",
				        "V12.9",
				        "V13",
				        "V13.0",
				        "V13.1",
				        "V13.2",
				        "V13.28",
				        "V13.3",
				        "V13.4",
				        "V13.40",
				        "V13.41",
				        "V13.48",
				        "V13.5",
				        "V13.9",
				        "V14.0",
				        "V14.4",
				        "V14.41",
				        "V14.48",
				        "V14.5",
				        "V14.9",
				        "V15.4",
				        "V16.0",
				        "V16.1",
				        "V16.2",
				        "V16.4",
				        "V16.5",
				        "V16.9",
				        "V17",
				        "V17.0",
				        "V17.01",
				        "V17.1",
				        "V17.2",
				        "V17.3",
				        "V17.4",
				        "V17.41",
				        "V17.48",
				        "V17.5",
				        "V17.9",
				        "V18",
				        "V18.0",
				        "V18.00",
				        "V18.01",
				        "V18.08",
				        "V18.1",
				        "V18.2",
				        "V18.3",
				        "V18.4",
				        "V18.41",
				        "V18.48",
				        "V18.49",
				        "V18.5",
				        "V18.9",
				        "V18.94",
				        "V19",
				        "V19.0",
				        "V19.03",
				        "V19.2",
				        "V19.3",
				        "V19.30",
				        "V19.38",
				        "V19.4",
				        "V19.6",
				        "V19.60",
				        "V19.62",
				        "V19.8",
				        "V19.80",
				        "V19.9"
				    },
				    pedestrian_list = {
				        "V00.00",
				        "V00.01",
				        "V00.02",
				        "V00.04",
				        "V00.05",
				        "V00.11",
				        "V00.12",
				        "V00.13",
				        "V00.14",
				        "V00.15",
				        "V00.18",
				        "V00.90",
				        "V00.92",
				        "V00.99",
				        "V01",
				        "V01.0",
				        "V01.00",
				        "V01.01",
				        "V01.03",
				        "V01.08",
				        "V01.1",
				        "V01.9",
				        "V02",
				        "V02.0",
				        "V02.00",
				        "V02.1",
				        "V02.10",
				        "V02.9",
				        "V03",
				        "V03.0",
				        "V03.00",
				        "V03.01",
				        "V03.08",
				        "V03.09",
				        "V03.1",
				        "V03.10",
				        "V03.11",
				        "V03.18",
				        "V03.19",
				        "V03.9",
				        "V03.90",
				        "V03.99",
				        "V04",
				        "V04.0",
				        "V04.1",
				        "V04.10",
				        "V04.11",
				        "V04.14",
				        "V04.18",
				        "V04.9",
				        "V05.0",
				        "V05.08",
				        "V05.1",
				        "V05.18",
				        "V05.9",
				        "V06.0",
				        "V06.1",
				        "V06.9",
				        "V09.0",
				        "V09.09",
				        "V09.1",
				        "V09.2",
				        "V09.3",
				        "V09.9",
				        "V09.99"
				    },
				    #"Added Conditional Column" =
				        Table.AddColumn(
				            Source,
				            "Cause",
				            each
				                if
				                    List.Contains(
				                        assault_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "Assault"
				                else if
				                    List.Contains(
				                        high_fall_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "High fall >1m"
				                else if
				                    List.Contains(
				                        low_fall_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "Low Fall"
				                else if
				                    List.Contains(
				                        motor_vehical_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "Motor Vehicle Driver/Passenger"
				                else if
				                    List.Contains(
				                        motorcycle_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "Motorcycle rider/pillion"
				                else if
				                    List.Contains(
				                        pedal_cyclist_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "Pedal cyclist"
				                else if
				                    List.Contains(
				                        pedestrian_list,
				                        [cause_icd_code_id]
				                    )
				                then
				                    "Pedestrian"
				                else
				                    "Other",
				            type text
				        ),
				    look_up_cause = [#"Motor Vehicle Driver/Passenger"=1, #"Motorcycle rider/pillion"=2, #"Pedal cyclist"=3,#"Pedestrian"=4,Assault=5,#"High fall >1m"=6, Low Fall=7, Other = 8],
				    look_up_transport = [#"Motor Vehicle Driver/Passenger"="Transport", #"Motorcycle rider/pillion"="Transport", #"Pedal cyclist"="Transport",#"Pedestrian"="Transport",Assault="Non Transport",#"High fall >1m"="Non Transport", Low Fall="Non Transport", Other = "Non Transport"],
				    #"Added Custom" = Table.AddColumn(#"Added Conditional Column", "cause_order", each Record.Field(look_up_cause,[Cause]), Int64.Type),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Transport", each Record.Field(look_up_transport, [Cause]), type text),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Added Custom1", "Transport", "Transport - order"),
				    #"Replaced Value1" = Table.ReplaceValue(#"Duplicated Column1","Non Transport","2",Replacer.ReplaceText,{"Transport - order"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value1","Transport","1",Replacer.ReplaceText,{"Transport - order"})
				in
				    #"Replaced Value"
				```

	annotation PBI_ResultType = Table

