/// Reference table containing ICD-10-AM (International Classification of Diseases, 10th Revision, Australian Modification) codes. Used to classify and code diagnoses and medical conditions in the trauma data.
table ICD-10-AM
	excludeFromModelRefresh
	lineageTag: 95f44289-ae58-40ef-83be-c73ad90dfe26

	/// ICD-10-AM diagnosis code. Standardized medical classification code used in Australian healthcare for diagnoses and medical conditions.
	column icd_code
		dataType: string
		lineageTag: a5cc4bb8-2e86-4c81-9e0c-1d986e15a7bf
		summarizeBy: none
		sourceColumn: icd_code

		annotation SummarizationSetBy = Automatic

	/// Description of the ICD-10-AM code. User-friendly explanation of the medical diagnosis or condition represented by the code.
	column icd_code_description
		dataType: string
		lineageTag: 461d76f9-235c-4019-a927-88962ff22ea6
		summarizeBy: none
		sourceColumn: icd_code_description

		annotation SummarizationSetBy = Automatic

	partition ICD-10-AM = m
		mode: import
		queryGroup: Source\ICD-10-AM/ACHI
		source =
				let
				    Source = Pdf.Tables(File.Contents(data_path&"icd-10-am_chronicle_-_eleventh_edition.pdf"), [Implementation="1.3"]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Kind] = "Table")),
				    #"Inserted Text After Delimiter" = Table.AddColumn(#"Filtered Rows", "Text After Delimiter", each Text.AfterDelimiter([Id], "Table"), type text),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Inserted Text After Delimiter",{{"Text After Delimiter", Int64.Type}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type1", each [Text After Delimiter] <= 1285 and [Text After Delimiter] >= 4),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows1",{"Data"}),
				    #"Expanded Data" = Table.ExpandTableColumn(#"Removed Other Columns", "Data", {"Column1", "Column2"}, {"Column1", "Column2"}),
				    #"Cleaned Text" = Table.TransformColumns(#"Expanded Data",{{"Column1", Text.Clean, type text}, {"Column2", Text.Clean, type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Cleaned Text",{{"Column1", Text.Trim, type text}, {"Column2", Text.Trim, type text}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Trimmed Text",{{"Column1", type text}, {"Column2", type text}}),
				    #"Filtered Rows2" = Table.SelectRows(#"Changed Type", each not (Text.Contains([Column1], "Chapter")or Text.Contains([Column1], "-"))),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows2",{{"Column1", "icd_code"}, {"Column2", "icd_code_description"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

