/// Reference table mapping ICD-10 codes between Victorian Emergency Minimum Dataset (VEMD) and ATR coding systems. Used to standardize and translate medical codes across different data sources.
table icd_10_vemd_atr_code
	lineageTag: f34c39f3-a0c8-459f-9d16-a6de45477f6b

	/// ICD-10 international classification code. Standardized medical code used globally to classify diseases, injuries, and health conditions.
	column 'ICD10 Code'
		dataType: string
		lineageTag: 1df8ff7f-7ef3-4e0f-816e-e9f96ca2fbc5
		summarizeBy: none
		sourceColumn: ICD10 Code

		annotation SummarizationSetBy = Automatic

	/// Description of the ICD-10 code. User-friendly text explaining the medical condition, injury, or diagnosis represented by the code.
	column Description
		dataType: string
		lineageTag: 91fbefb3-6ad0-42cd-879e-ae0239c61810
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	/// Victorian Emergency Minimum Dataset code number. Victoria-specific emergency department coding system used to classify presentations and injuries.
	column 'VEMD Code'
		dataType: int64
		formatString: 0
		lineageTag: 444f87eb-53ce-43b3-8685-c97c19022ed8
		summarizeBy: count
		sourceColumn: VEMD Code

		annotation SummarizationSetBy = Automatic

	/// Australian Trauma Registry code number. ATR-specific coding value used to classify trauma cases, mapped from ICD-10 and VEMD codes for consistency.
	column 'ATR Code'
		dataType: int64
		formatString: 0
		lineageTag: f939b948-d19e-4178-967d-f0b17a01e268
		summarizeBy: count
		sourceColumn: ATR Code

		annotation SummarizationSetBy = Automatic

	partition icd_10_vemd_atr_code = m
		mode: import
		queryGroup: Pre-process
		source =
				let
				    Source = #"VOTOR_ICDevent_Mapping_ATR mapping",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"ICD10 Code", "Description", "VEMD Code", "ATR Code"}),
				    #"Appended Query" = Table.Combine({#"Removed Other Columns", Merge1}),
				    #"Sorted Rows" = Table.Sort(#"Appended Query",{{"ICD10 Code", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

