table '07_ATRCompleteDataset (2)'
	lineageTag: f8a62717-4ffb-4609-a12a-a4571e2ff03e

	measure records = sum('07_ATRCompleteDataset (2)'[Count])
		lineageTag: 94cafdfd-d19f-4492-bff8-845d44c2cdf0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DOIJ
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28f43530-6b3b-4ca6-9473-c82f16a825be
		summarizeBy: none
		sourceColumn: DOIJ

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column InjuryPlace
		dataType: string
		lineageTag: 39dbbc7c-2a6f-459e-a54c-570f01bdc245
		summarizeBy: none
		sourceColumn: InjuryPlace

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: 0
		lineageTag: e389e438-8cf0-45f9-b2cc-a8049d5a1d02
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	partition '07_ATRCompleteDataset (2)' = m
		mode: import
		queryGroup: DEV
		source =
				let
				    Source = #"07_ATRCompleteDataset",
				    #"Filtered Rows" = Table.SelectRows(Source, each List.ContainsAny({[InjuryPlace]},{"-99","W92.5","Y29.9","Y34.0","Y92.23","Y92.24"})),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"DOIJ", "InjuryPlace"}),
				    #"Extracted Date" = Table.TransformColumns(#"Removed Other Columns",{{"DOIJ", DateTime.Date, type date}}),
				    #"Calculated Start of Month" = Table.TransformColumns(#"Extracted Date",{{"DOIJ", Date.StartOfMonth, type date}}),
				    #"Grouped Rows" = Table.Group(#"Calculated Start of Month", {"DOIJ", "InjuryPlace"}, {{"Count", each Table.RowCount(_), Int64.Type}})
				in
				    #"Grouped Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

