table DIM_INJURY_CAUSE
	lineageTag: 3c833ef7-1be0-48bb-86e0-9c202ea3e667

	column cause_order
		dataType: int64
		formatString: 0
		lineageTag: 93fb2a52-fc52-47c8-b0ce-aaf81f03d20e
		summarizeBy: none
		sourceColumn: cause_order

		annotation SummarizationSetBy = Automatic

	column Transport
		dataType: string
		lineageTag: 7be07030-6433-4c9f-aef5-5718fcc4b7d9
		summarizeBy: none
		sourceColumn: Transport

		annotation SummarizationSetBy = Automatic

	column 'Transport - order'
		dataType: string
		lineageTag: e7d2494c-1974-4b12-8b1e-264602abe123
		summarizeBy: none
		sourceColumn: Transport - order

		annotation SummarizationSetBy = Automatic

	column cause_code_atr
		dataType: string
		lineageTag: b347b479-43b5-4e8e-a0ac-cd6475fde34f
		summarizeBy: none
		sourceColumn: cause_code_atr

		annotation SummarizationSetBy = Automatic

	column cause_icd_code_id
		dataType: string
		lineageTag: d426d35f-5339-45fe-be54-ddc9b6b74e9d
		summarizeBy: none
		sourceColumn: cause_icd_code_id

		annotation SummarizationSetBy = Automatic

	column icd_code_description
		dataType: string
		lineageTag: 1ddfc665-5a2f-47f1-9883-97b1587a64e9
		summarizeBy: none
		sourceColumn: icd_code_description

		annotation SummarizationSetBy = Automatic

	column 'ATR Code'
		dataType: int64
		formatString: 0
		lineageTag: 18beb700-d6f1-4db4-964f-40d5f9cddb26
		summarizeBy: none
		sourceColumn: ATR Code

		annotation SummarizationSetBy = Automatic

	column atr_description
		dataType: string
		lineageTag: 9ba59b3e-cf61-4ab3-b16b-0da595b3e912
		summarizeBy: none
		sourceColumn: atr_description

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"DIM_INJURY_CAUSE","TableItemName":"atr_description (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 'atr_description (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('DIM_INJURY_CAUSE'[atr_description]),
				"(Blank)",
				'DIM_INJURY_CAUSE'[atr_description] IN {"High fall >1m"},
				"High fall >1m",
				'DIM_INJURY_CAUSE'[atr_description] IN {"Low Fall"},
				"Low Fall",
				'DIM_INJURY_CAUSE'[atr_description] IN {"Motor Vehicle Driver/Passenger"},
				"Motor Vehicle Driver/Passenger",
				'DIM_INJURY_CAUSE'[atr_description] IN {"Motorcycle rider/pillion"},
				"Motorcycle rider/pillion",
				'DIM_INJURY_CAUSE'[atr_description] IN {"Pedal cyclist"},
				"Pedal cyclist",
				'DIM_INJURY_CAUSE'[atr_description] IN {"Pedestrian"},
				"Pedestrian",
				"Other"
			)
		lineageTag: 7b9d561f-af34-4a1b-b3ec-b91a349fba99
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "DIM_INJURY_CAUSE"
				          }
				        },
				        "Property": "atr_description"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"DIM_INJURY_CAUSE"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"High fall >1m","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"Values":[[{"Literal":{"Value":"'High fall >1m'"}}]]}}},{"DisplayName":"Low Fall","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"Values":[[{"Literal":{"Value":"'Low Fall'"}}]]}}},{"DisplayName":"Motor Vehicle Driver/Passenger","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"Values":[[{"Literal":{"Value":"'Motor Vehicle Driver/Passenger'"}}]]}}},{"DisplayName":"Motorcycle rider/pillion","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"Values":[[{"Literal":{"Value":"'Motorcycle rider/pillion'"}}]]}}},{"DisplayName":"Pedal cyclist","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"Values":[[{"Literal":{"Value":"'Pedal cyclist'"}}]]}}},{"DisplayName":"Pedestrian","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"atr_description"}}],"Values":[[{"Literal":{"Value":"'Pedestrian'"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

	hierarchy 'Transport Hierarchy'
		lineageTag: b0012c44-0424-4bcb-aa9f-68ee769ebb42

		level Transport
			lineageTag: 01479165-d072-4274-9dd4-6836d5a4ce16
			column: Transport

	partition DIM_INJURY_CAUSE-58cbba83-91ef-4dc9-b388-76564cf898f9 = m
		mode: import
		queryGroup: Dimension
		source = ```
				let
				    Source = Table.NestedJoin(injury_cause, {"cause_code_atr"}, cause_code_lookup, {"ICD10 Code"}, "cause_code_lookup", JoinKind.LeftOuter),
				    #"Expanded cause_code_lookup" = Table.ExpandTableColumn(Source, "cause_code_lookup", {"ATR Code"}, {"ATR Code"}),
				    #"Merged Queries" = Table.NestedJoin(#"Expanded cause_code_lookup", {"ATR Code"}, look_up_cause_description, {"atr_code"}, "look_up_cause_description", JoinKind.LeftOuter),
				    #"Expanded look_up_cause_description" = Table.ExpandTableColumn(#"Merged Queries", "look_up_cause_description", {"atr_description"}, {"atr_description"}),
				    
				    look_up_cause = [#"Motor Vehicle Driver/Passenger" = 1,
					#"Motorcycle rider/pillion" = 2,
					#"Pedal cyclist" = 3,
					#"Pedestrian" = 4,
					#"Other Transport Related" = 5,
					#"Horse-related" = 6,
					#"High fall >1m" = 7,
					#"Low Fall" = 8,
					#"Striking against or by object" = 9,
					#"Struck by or Collision with a Person" = 10,
					#"Cutting, Piercing Object" = 11,
					#"Submersion or Drowning" = 12,
					#"Other Threat to Breathing" = 13,
					#"Fire, Flames, Smoke" = 14,
					#"Firearm" = 15,
					#"Other" = 16,
					#"Unknown" = 17],
				    look_up_transport = [
				    #"Motor Vehicle Driver/Passenger" = "Transport",
					#"Motorcycle rider/pillion" = "Transport",
					#"Pedal cyclist" = "Transport",
					#"Pedestrian" = "Transport",
					#"Other Transport Related" = "Transport",
					#"Horse-related" = "Non Transport",
					#"High fall >1m" = "Non Transport",
					#"Low Fall" = "Non Transport",
					#"Striking against or by object" = "Non Transport",
					#"Struck by or Collision with a Person" = "Non Transport",
					#"Cutting, Piercing Object" = "Non Transport",
					#"Submersion or Drowning" = "Non Transport",
					#"Other Threat to Breathing" = "Non Transport",
					#"Fire, Flames, Smoke" = "Non Transport",
					#"Firearm" = "Non Transport",
					#"Other" = "Non Transport",
					#"Unknown" = "Non Transport"
				    ],
				    #"Added Custom" = Table.AddColumn(#"Expanded look_up_cause_description", "cause_order", each Record.Field(look_up_cause,[atr_description]), Int64.Type),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Transport", each Record.Field(look_up_transport, [atr_description]), type text),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Added Custom1", "Transport", "Transport - order"),
				    #"Replaced Value1" = Table.ReplaceValue(#"Duplicated Column1","Non Transport","2",Replacer.ReplaceText,{"Transport - order"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Replaced Value1","Transport","1",Replacer.ReplaceText,{"Transport - order"}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Replaced Value", {{"cause_order", null}, {"Transport", null}, {"Transport - order", null}}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Errors", {"cause_icd_code_id"})
				in
				    #"Removed Duplicates"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

